{% set name = "felyx-report" %}
{% set version = "1.1.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/felyx/felyx_report/-/archive/{{ version }}/felyx_report-{{ version }}.tar.gz
  sha256: 7779a451d02b02bc75e64fc4904afcdedcd0e4e835ba118c47453c48f4533aed

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 5
  noarch: python
  entry_points:
    - felyx-report = felyx_report.cli.main:felyx_monitoring_report

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
  run:
    - python >={{ python_min }}
    - elasticsearch ==7.17.0
    - grafana-client >=3.5
    - pyarrow >=17.0,<18.0
    - pydantic ==2.9.1
    - pydantic-settings >=2.4.0,<3.0.0
    - numpy >=1.22.2
    - pandas >=2.2
    - pyyaml >=6.0,<7.0
    - shapely ==2.0.6
    - xarray >=2024.10.0
    - netcdf >=1.5.4
    - jinja2 >=3.1.2,<3.2
test:
  requires:
    - python {{ python_min }}
  imports:
    - felyx_report

about:
  home: https://gitlab.ifremer.fr/felyx/felyx_report
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Produce monitoring report from data processed by Felyx processor

extra:
  recipe-maintainers:
    - erwanbodere
    - cso2943
    - criou-cg
    - marie59
